# Generated by Django 5.1 on 2024-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('lang', models.CharField(max_length=50, verbose_name='Language')),
                ('uid', models.CharField(max_length=200, verbose_name='User ID')),
                ('room_name', models.CharField(max_length=200, verbose_name='Room Name')),
            ],
            options={
                'verbose_name': 'Room Member',
                'verbose_name_plural': 'Room Members',
            },
        ),
    ]
